changelog:
  exclude:
    labels:
      - ignore-for-release-notes
    authors:
      - MobiFlight-Admin
  categories:
    - title: New Feature 🎉
      labels:
        - feature
    - title: Improvement ✨
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Documentation 📚
      labels:
        - documentation
    - title: Development 💻
      labels:
        - development    
    - title: Bug Fixes (BETA) 🐛
      labels:
        - bug_beta
        - beta-bug
    - title: Other Changes ⚡
      labels:
        - "*"